### ISSUE TITLE
support i3

### ISSUE THREAD

**Issue by isaiahr** [JSpeedie/dotfiles#7]
py an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program.

  You may charge any price or no price for each copy that you convey,
and you may offer support or warranty protection for a fee.

  5. Conveying Modified Source Versions.

  You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of t

**Comment by JSpeedie** [comment]
Thanks for that.

**Comment by isaiahr** [comment]
,,,,
